title: lachrist's blog
encoding: utf-8
email: laurent.christophe.terken@gmail.com
description: This my attempt at broadcasting mostly coding-related stuff to the world.
source: source
destination: _site
baseurl: ""
url: "https://lachrist.github.io"
github_username: lachrist
theme: minima
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude: []
markdown_ext: md
collections:
  blog:
    output: true
    permalink: pretty
