title: lachrist
author: Laurent Christophe
encoding: utf-8
email: laurent.christophe@vub.be
description: "Laurent Christophe's personal page"
url: "https://lachrist.github.io"
linkedin_username: lachrist
github_username: lachrist
theme: minima
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
markdown_ext: md
header_pages:
  - repo.md
  - blog.md
  - resume.md
  - resources.md
collections:
  drafts:
    output: false
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
